functionsDirectory = "C:\\Users\\frans\\Desktop\\Egna\\ Projekt\\BootlegSteam\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\frans\\Desktop\\Egna\\ Projekt\\BootlegSteam\\dist"
publishOrigin = "config"
from = "/*"
to = "/index.html"
status = 200.0
command = "npm run build"
commandOrigin = "config"
functions = "C:\\Users\\frans\\Desktop\\Egna Projekt\\BootlegSteam\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]